spring:
  application:
    name: rest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Trainee
    username: root
    password: 0906
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    allow-bean-definition-overriding: true

